### ISSUE TITLE
不知不觉已经升级到 24.1.0 版本了，一切正常，感谢@hzhr的解决方案

### ISSUE THREAD

**Issue by liujing0735** [Semporia/TikTok-Unlock#136]
可能21.1直接到23.4版本跨度太大了，有些什么配置重置了导致不行，可能此github仓主是小版本一个个升上来的，他这没问题。
我这之前也有这样问题，直升到23.4不行。然后折腾一番操作后又可以了，下面说说，看你们这行不行。

首先确实21.1开始强制升级了，但似乎是针对未登录用户的，此时只要快速切到个人主页，注册账号登录（我用Apple账号匿名注册），发现不会再强制升级了，而且可以稳定使用。
其次看着红点总不爽，仓主又说可以用，于是决定升级到23.4，确实升完后第一次打开可以用，但是杀掉重开，马上就不行了。
此时，不要卸载app、不要卸载、不要卸载，手机连mac用Apple Configurator 2把老的21.1的ipa拖进去，强制降级版本。
降级完成后，21.1版本第一次打开也不行，杀掉重开，结果马上恢复变好了。
最后，再从21.1升级到23.4，升级完到现在还稳定使用中。。。
今天又从23.4升了一下到23.5，目前看能继续使用，没有问题，观察几天看。

要点：升级后如果不能使用，不要卸载，强制降级到21.1，等可用后再次升级就没问题了。不太确定是否必须要登录账号，可以试试。

_Originally posted by @hzhr in https://github.com/Semporia/TikTok-Unlock/issues/134#issuecomment-1063673706_

**Comment by liujing0735** [comment]
按这个方法操作可行，感谢！

**Comment by liujing0735** [comment]
3月18日升级到23.6.0，一切正常

**Comment by seoho8908** [comment]
> 3月18日升级到23.6.0，一切正常

有反馈23.6更新后无法使用。

**Comment by hzhr** [comment]
> > 3月18日升级到23.6.0，一切正常
> 
> 有反馈23.6更新后无法使用。

我升级了一下23.6，目前看也是好的。你要不试试上面方法看行不行。

**Comment by lustb0y** [comment]
> > > 3月18日升级到23.6.0，一切正常
> > 
> > 
> > 有反馈23.6更新后无法使用。
> 
> 我升级了一下23.6，目前看也是好的。你要不试试上面方法看行不行。

老哥能加个联系方式请教一下吗？我扣扣1610469872

**Comment by lustb0y** [comment]
老哥你好，我的问题是我用iTunes装21.1一直都是授权，然后我把21.1的ipa安装包用iamazing装到手机上，然后打开tiktok能看到一个在加载中的视频，之后就没了，我怀疑是我的小火箭没有配置好，我整了个圈X还是不行------------------ 原始邮件 ------------------发件人: 山河无恙  ***@***.***>发送时间: 2022年3月21日 09:26收件人: Semporia/TikTok-Unlock ***@***.***>抄送: coochiehoney ***@***.***>, Comment ***@***.***>主题: Re: [Semporia/TikTok-Unlock] ***@***.***的解决方案 (Issue #136)
3月20日升级到23.7.0，一切正常

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Semporia/TikTok-Unlock/issues/136#issuecomment-1073403113",
"url": "https://github.com/Semporia/TikTok-Unlock/issues/136#issuecomment-1073403113",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by qin9125** [comment]
这个方法似乎不行了，我今天不小心裸连本地网后黑屏，卸载重新安装 21.1 用这方法升级 2.39 第二次覆盖结束后台打开依旧黑屏

**Comment by nuaalm** [comment]
> 这个方法似乎不行了，我今天不小心裸连本地网后黑屏，卸载重新安装 21.1 用这方法升级 23.9 第二次覆盖结束后台打开依旧黑屏

是不行的

**Comment by liujing0735** [comment]
如果还不行的，需要再确认以下几个问题：
1、机场环境，换机场、换美、日、韩等线路都试试；
2、降级和升级的安装包（本人提取了21.1和23.9）一定要登录自己的apple id 提取;
3、务必先开圈X，再打开tiktok；
4、我之前也是播不了，各种尝试，目前用此方法已经升级到24.1了，使用正常，但不保证大家都有效，因为别人说有效的，对我来说又不行~~~

**Comment by liujing0735** [comment]
close
